### ISSUE TITLE
Анимации ссылок, карточек, заголовков, меню

### ISSUE THREAD

**Issue by dobrodob** [Discours/discours-welcome#37]
- [ ] Стиль подчеркивания и анимации ссылок в основном тексте. Как на старом Дискурсе?
- [ ] Анимация карточек на главной
- [ ] Анимация пунктов в меню
- [ ] И другие анимации)

**Comment by famadihana** [comment]
https://www.figma.com/file/YoD2Kjr4kim0rBTrOqRn1O/Discours?node-id=917%3A4503

Как на старом дискурсе, но немного другие отступы

**Comment by famadihana** [comment]
Посмотри, зайди на главную в фигме, описал. Чего не хватает?

**Comment by dobrodob** [comment]
Круто! Не хватает только наведений на разделы и иконки в меню и в футтере
