### ISSUE TITLE
Главная: Сделать блок «Интересные темы»

### ISSUE THREAD

**Issue by dobrodob** [Discours/discours-welcome#38]
Этот блок временно ставим его на место блока “Интересные сообщества”; в будущем будем использовать оба — в колонке ленты, в рекоммендациях и т.д.)
Вот это место на https://new.discours.io/

**Comment by famadihana** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/55750147/150018685-c2eaef33-f544-4e76-8a8f-24f13b0a04ed.png">
не понимаю что за блок. вот это место? это взято из макетов откуда-то из другого места, не со страницы с главной в фигме?
