### ISSUE TITLE
Корректировка верстки: главная, темы, профиль, About

### ISSUE THREAD

**Issue by dobrodob** [Discours/discours-welcome#65]

**Comment by dobrodob** [comment]
@kvakazyambra привет! Буду собирать здесь для тебя все правки по вёрстке :)

**▶️Next**
- [x] 1. Главная. Блок 'Интересные темы' стилизуем под макет - выводим больше тем (пять вместо трёх), отображаем количество публикаций, выводим описание темы (если есть), кнопку 'подписаться' сдвигаем влево. [Картинка](https://user-images.githubusercontent.com/47947996/171185975-677ebd9a-f2fa-4936-946b-e96b456aabfe.png)
- [x] 2. Главная. Блок 'Случайная тема' пока на себя не похож - иногда там бывает только один материал, а должны появляться последние 9 материалов по одной из живых тем, в которых больше 20 материалов. [Картинка](https://user-images.githubusercontent.com/47947996/171185978-a4e83c39-d62e-43f2-9c38-daf78df946ba.png)
- [x] 3. [Главная: в баннере уменьшаем черные поля на десктопе в два раза и на треть отступы между заголовком, подзаголовком и кнопками](https://user-images.githubusercontent.com/47947996/174625904-29f92c09-c395-425d-9835-a05041ffba4c.png)
- [x] 4. Главная. Mobile fixes: 
- [x] 4.1 [Mobile: в слайдерах текст не помещается. Чтобы было красивее, давай поставим текст ближе к низу карточки и расширим всю картинку центрального поста в слайдерах](https://user-images.githubusercontent.com/47947996/174625889-fe5978dd-df70-4ab5-b038-f01f919295ab.png)
- [x] 4.2 [Mobile: уменьшаем на мобильных стандартный отступ между карточками в два раза](https://user-images.githubusercontent.com/47947996/174625902-06e06d58-645f-48be-a6c5-291a174f81bb.png)
- [x] 4.3 [Mobile - встречается очень узкий формат карточек, такие не делаем  Делаем картинку стандартных пропорций](https://user-images.githubusercontent.com/47947996/174625899-45dd3c67-9dde-444b-bb27-0e8e36cd006b.png)
- [ ] 5. Темы по алфавиту. а) добавляем поле поиска; б) классно было бы добавить алфавитное оглавление с якорными ссылками; в) заметил что в одном месте ломается. [Картинка](https://user-images.githubusercontent.com/47947996/171285343-27ff5fa3-97d1-4a92-b8d5-d8f1bba3cf7d.png)
- [x] 6.1 Темы. В анимации при наведении текст на чёрной заливки хорошо бы инвертировать в белый, а то его не видно. [Картинка](https://user-images.githubusercontent.com/47947996/172224757-6f666375-2691-40d5-a956-744f069443f5.jpg)
- [x] 6.2 [Темы  Двухколоночная аномалия](https://user-images.githubusercontent.com/47947996/174625910-85b8da98-0937-4c24-8e52-2929dc0bd3f8.png)
- [x] 7. Профиль. Блок 'Автор поддерживает темы'. а) Сокращаем видимое описание тем до 70 символов; б) Убираем отображение количества подписчиков. [Картинка](https://user-images.githubusercontent.com/47947996/172225373-c80da4b7-0ca4-4c7c-98af-5584ce5f7551.png)
- [ ] 8. [Профиль: реальные тексты "о себе" пока не выводятся и "кармы" не хватает](https://user-images.githubusercontent.com/47947996/174625908-76a0b5f6-f3a3-4a24-9719-174cdd9c2fd7.jpg)
- [ ] 9. Страницы 'О проекте' стилизуем по [Фигме 'Discours Статья'](https://www.figma.com/file/PnpCL9Upy66xouAGaihEaH/Discours-%D0%A1%D1%82%D0%B0%D1%82%D1%8C%D0%B8?node-id=0%3A1) (заголовки делаем на плашках; добавляем к подзагам спойлеры). [Картинка](https://user-images.githubusercontent.com/47947996/171185977-32326801-f577-4d6f-a0b6-bba0443337b4.png)
- [ ] 10. Главная: карточки и анимации
- [x] 10.1. Подзаголовки тоже анимируем! При наведении на карточку всегда (картинку, заг, подзаг) анимируем целиком и заголовок, и подзаголовок — всё заливаем [белым выделением и инвертируем в черный текст на черном фоне](https://user-images.githubusercontent.com/47947996/175400623-753a5c1d-3461-43d5-b1f9-ee02ce959531.png) и наоборот соответственно [на белом фоне](https://user-images.githubusercontent.com/47947996/175400644-639c87e4-10f3-4345-ba52-dd8bfc317a19.png)
- [x] 10.2. При наведении в разных местах иногда полосы заливки закрывают буквы. А лучше бы буквам быть сверху и всегда оставаться видимыми: [картинка](https://user-images.githubusercontent.com/47947996/175400639-df2818cf-5bdc-46a0-b481-3b59c365178e.png)
- [ ] X. При загрузке страниц отображать линию прогрузки в меню (как на старом Дискурсе) и по середине странице показывать анимацию загрузки (вращающийся кружек синхронизации из font-awesome, например)


**⏲️Later**
...


**✔️Done**
- [x] 0. Хорошо бы во время загрузки страниц [показывать](https://user-images.githubusercontent.com/47947996/171185972-b3d269bd-2583-44cb-a92e-ac4b21f027de.png) футтер внизу экрана
- [x] 1. Во втором меню в шапке а) выводим больше тем; б) даём кнопку 'все темы'. [Скриншот](https://user-images.githubusercontent.com/47947996/171185968-8f756d06-c735-4252-a45f-22e875672279.png)
- [x] 2. Шапка - обрезаем концы у линии. [Скриншот](https://user-images.githubusercontent.com/47947996/171185980-5bba2706-0e60-4015-a104-113b5066dd74.png)
- [x] 3. Имена уменьшаем и делаем серыми. [Картинка](https://user-images.githubusercontent.com/47947996/171185965-7ddae89c-f433-4869-8a81-92e274483eeb.png)
- [x] 4. В баннере тексты и кнопки равняем по центру страницы + Уменьшаем отступ над баннером. [Картинка](https://user-images.githubusercontent.com/47947996/171185971-122e0ee8-dcde-4584-9965-0c398cc9a7c1.png)
- [x] 5. Блок самое читаемое. Здесь должны быть самые просматриваемые публикации последнего месяца (вместо тем). И по-другому оформленные. [Картинка](https://user-images.githubusercontent.com/47947996/171185967-4888289d-2a66-48ec-a12b-d95da59235b4.png)
- [x] 6. У карточки 2-3 другие стили заголовка и подзаголовка. [Картинка](https://user-images.githubusercontent.com/47947996/171185970-e34f5f55-581d-4998-ac20-efb2c914928d.png)
- [x] 7. Карточки 1-3. Уточняем стиль заголовков и подзаголовков. [Картинка](https://user-images.githubusercontent.com/47947996/171185976-40b74f3f-e2e6-45f4-bc14-6cc9d7464c81.png)
- [x] 8. Авторы месяца — а) переименовываем в 'Популярные авторы'; б) выводим 5; в) оформляем немного иначе (без цифры, но с кнопкой подписки). [Картинка](https://user-images.githubusercontent.com/47947996/171185966-9d06631e-ec47-4ea5-9021-6e0d189448d4.png)
- [x] 9. Слайдеры. а) Стрелки развернуть в другие стороны; б) сделать сильно уже по высоте; в) добавить 3-й видимый материал. [Картинка](https://user-images.githubusercontent.com/47947996/171185969-bcc9c887-52dc-4ac1-8902-c05baa10e8d7.png)
- [x] 10. На карточках с текстом поверх картинок имена авторов пишем белым (иначе не видно на тени). [Картинка](https://user-images.githubusercontent.com/47947996/171185973-37554e1f-c84a-4afc-82f0-38a55869872e.png)
- [x] 13. Страница публикации в mobile-версии гораздо уже, чем весь остальной сайт — давайте её полноценно расширим. [Картинка](https://user-images.githubusercontent.com/47947996/171218021-fa01cff8-6304-4198-a0f2-78d3a92aff92.jpg)
- [x] 15. Настроить zoom-анимацию при наведении на карточки (как на старом сайте Дискурса)
- [x] 16. Подвал - в поле подписки добавляем кнопку. [Картинка](https://user-images.githubusercontent.com/47947996/171185974-e74a3ba7-777b-424f-9419-3a012927e0c8.png)
*Темы*
- [x] 18. Темы. Страница с алфавитом едет. [Картинка](https://user-images.githubusercontent.com/47947996/171185979-87f57840-4d6f-4fa9-ad48-20c0168b21dd.png)
- [x] 20. Темы по алфавиту. Шапку и начало колонок с темами сдвигаем левее по линии начала меню (эта опорная точка у нас ещё будет встречаться). Буквы оставляем на месте для наглядной навигации. [Картинка](https://user-images.githubusercontent.com/47947996/171285340-b3381eca-d912-4f1a-97bc-cd30a9f119a8.png)
- [x] 21. Темы по просмотрам и по популярности. Начинаем основной контент страницы тем с опорной линии начала меню. [Картинка](https://user-images.githubusercontent.com/47947996/171285342-042f0339-6cc0-4d17-9a2c-8f1d44cbba12.png)
- [x] 22. Темы. При наведении на уже выбранный раздел он не доконца анимируется — заливается черным, а шрифт белым не становится. [Картинка](https://user-images.githubusercontent.com/47947996/171285341-58eccdcc-4fe2-44a8-a3de-2c19e79f31cb.png)
*Профиль**
- [x] 24. Профиль. а) верстаем кнопки 'Подписаться' и 'Написать; б) выводим базовую инфу, которая уже есть на старом Дискурсе - Информация о себе; Ссылки на соцсети; Карма. [Картинка](https://user-images.githubusercontent.com/47947996/172225340-159f796d-51b8-4564-a74a-139399c6031a.png)

**Comment by dobrodob** [comment]
@kvakazyambra обновил! Кажется, удобнее сам список сделал и, пройдясь по нашим красотам, новые пункты добавил)

**Comment by tonyrewin** [comment]
Блок 'Случайная тема' убираем ваще

**Comment by kvakazyambra** [comment]
8 - текстов об авторе нет в данных, а кармы нет в макете
